"""initial_schema

Revision ID: 63eebdf4bf2e
Revises: 
Create Date: 2026-03-15 01:21:37.967453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63eebdf4bf2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_returns_id'), table_name='tax_returns')
    op.drop_index(op.f('ix_tax_returns_session_id'), table_name='tax_returns')
    op.drop_table('tax_returns')
    op.drop_index(op.f('ix_tax_year_parameters_id'), table_name='tax_year_parameters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tax_year_parameters_id'), 'tax_year_parameters', ['id'], unique=False)
    op.create_table('tax_returns',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tax_year', sa.INTEGER(), nullable=False),
    sa.Column('personal_data', sa.TEXT(), nullable=True),
    sa.Column('income_data', sa.TEXT(), nullable=True),
    sa.Column('deduction_data', sa.TEXT(), nullable=True),
    sa.Column('result_data', sa.TEXT(), nullable=True),
    sa.Column('zve', sa.FLOAT(), nullable=True),
    sa.Column('total_tax', sa.FLOAT(), nullable=True),
    sa.Column('refund_or_payment', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_returns_session_id'), 'tax_returns', ['session_id'], unique=1)
    op.create_index(op.f('ix_tax_returns_id'), 'tax_returns', ['id'], unique=False)
    # ### end Alembic commands ###
